# Generated by Django 6.0.1 on 2026-01-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
