# Generated by Django 6.0.1 on 2026-01-11 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('days_of_week', models.CharField(default='Mon-Fri', max_length=64)),
                ('price_base', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gares.line')),
            ],
        ),
        migrations.CreateModel(
            name='LineStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gares.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gares.station')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('line', 'station')},
            },
        ),
        migrations.AddField(
            model_name='line',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_destination', to='gares.station'),
        ),
        migrations.AddField(
            model_name='line',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_origin', to='gares.station'),
        ),
        migrations.AddField(
            model_name='line',
            name='stops',
            field=models.ManyToManyField(related_name='lines', through='gares.LineStop', to='gares.station'),
        ),
    ]
