# Generated by Django 6.0.1 on 2026-01-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Voiture'), ('SEDAN', 'Berline'), ('SUV', '4x4'), ('MINIBUS', 'Minibus'), ('BUS', 'Bus rapide')], max_length=20)),
                ('mode', models.CharField(choices=[('PRIVATE', 'Privé'), ('SHARED', 'Partagé'), ('BUS', 'Bus')], default='PRIVATE', max_length=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['vehicle_type', 'mode', 'region'],
            },
        ),
    ]
